name: AWS OIDC Authentication Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  AuthenticateAWS:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::591563074970:role/gh-action-oidc-cloudwatch-logs
          aws-region: us-east-1

      - name: Verify Authentication
        run: aws sts get-caller-identity
