name: Runner
on:
  workflow_dispatch:
jobs:
  alpine-container-on-github-hosted-ubuntu-vm:
    
    name: Alpine container on Ubuntu VM
    runs-on: ubuntu-24.04
    container:
      image: alpine:3.20
    steps:
      - name: Show runner info
        run: |
          echo $GITHUB_WORKSPACE
          echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
          echo "Runner name (type): ${{ runner.name }}"
          echo "Container image:   $(grep PRETTY_NAME /etc/os-release)"
